@startuml obj-FHIR-data-screening-summary-basic

!define COMMON .

!include COMMON/component-skinparams.iuml

top to bottom direction
scale max 1000*1200
scale 600 width

'skinparam linetype ortho
skinparam dpi 200
skinparam nodesep 15 ' component left-right spacing
skinparam ranksep 5 ' component up-down spacing

allow_mixing

title FHIR instance data model - screening summary document

!procedure $Coding($Alias,$System,$Code,$Display)
object "<color:GhostWhite>$System" as $Alias #MediumPurple {
  <color:GhostWhite><size:11>**$Code**-$Display
}
!endprocedure

() "/DocumentReference endpoint" as BINAPI

interface FHIRAPI as "<size:16>FHIR screening summary API\n(convenience document variant)"

BINAPI -d- FHIRAPI

frame "screening summary FHIR data" as BINARY #GhostWhite {

  object "<size:14>**:DOCUMENTREFERENCE**" as DOCREF <<profiled>> #GhostWhite/LightCoral {
      * masterIdentifier: identifier
      * status: ""#current""
      * date: 2024-05-12 (UTC)
  }

  object ":ATTACHMENT" as DOC #GhostWhite {
      * data.base64Binary: base64-enc. PDF | HTML
      * creation: 2024-05-12T10-00-00Z (UTC)
      * size: nnn
      * contentType: application/pdf | text/html
  }

  object "NzPatient:PATIENT" as PATIENT #GhostWhite {
      * identifier: NHI reference
      * birthDate
      * ethnicity(extension)
      * address
  }

  DOCREF ".content\n.attachment" -d-* DOC
  DOCREF ".subject" --* PATIENT
}

$Coding(DocumentType,"Clinical document type (SNOMED)","#422735006","Summary clinical document     ")

$Coding(ProgrammeType,"Screening programme type (SNOMED screening services)","#1230046007","Cervical cancer screening service      ")
$Coding(ProgrammeType,"Screening programme type (SNOMED screening services)","#1163003002","Colorectal cancer screening service    ")
$Coding(ProgrammeType,"Screening programme type (SNOMED screening services)","#310126000", "Breast screening service               ")
$Coding(ProgrammeType,"Screening programme type (SNOMED screening services)","#310009009", "Neonatal audiological screening service")

' connectors
FHIRAPI -d- BINARY
DOCREF ".type" -[#MediumPurple,dotted]u-> DocumentType
DOCREF ".category" -[#MediumPurple,dotted]--> ProgrammeType



' legend
'   **Notes**
'endlegend

@enduml