@startuml seq-fhir-screening-API-typicaloperation

!define COMMON .
!include COMMON/sequence-skinparams.iuml

scale max 400 width
scale 300*500

actor "health practitioner (screening)" as USER
participant "practitioner's APP/PMS" as APIC #Orange

' box "HNZ digital services hub" #LightGrey
'   entity "API authn. server" as ROSIE #IndianRed
'   entity "API gateway" as APIG #IndianRed
' end box

box "HNZ FHIR APIs" #WhiteSmoke
  entity "**screening summary FHIR API**" as SCRAPI #LightSalmon
  entity "NHI FHIR API" as NHPIG
end box

title "Cervical screening summary - Typical API Operation"

== initialisation and prequisite API checks ==

note over APIC
  <size:20>Refer to authorization sequence diagram
end note

== normal API usage ==

USER -> APIC++ #YellowGreen: enter patient name, NHI
APIC -> NHPIG: NHI search
APIC -> USER--: present NHI matches

USER -> APIC++ #YellowGreen: request screening summaries for\n selected NHI and programme type 

note right of APIC
  ""Request-Context"" custom header must be setup by PMS/APP
    """userIdentifier""" - user Id as known/authenticated by the PMS/APP
    """userRole""" - the role of the user as defined by the PMS/APP
    """secondaryIdentifier""" - the user's health organisation as an HPI organisation identifier.
end note

APIC -> SCRAPI: ""GET"" /**DocumentReference**?<params>

note right
  search request query parameters:
  ""?"" **subject:identifier** = <NHI>
  ""&"" **category** = <screening service type SNOMED>
  ""&"" **contenttype** = ""application/pdf""
  ""&"" **_include** = **DocumentReference:subject**
end note

SCRAPI -> SCRAPI: validate OAUTH token\n<size:12>(issuer,token,scope,audience)</size>

SCRAPI -> SCRAPI: validate ""Request-Context"" custom header

alt #LightGreen normal report generation
SCRAPI -> SCRAPI: get data from backend APIs
SCRAPI -> SCRAPI: generate screening summary content as HTML and PDF
SCRAPI -> SCRAPI: include participant data as ""Patient"" instance
SCRAPI -> APIC: ""200 OK"", FHIR searchset ""Bundle"" 
  note left of SCRAPI #LightYellow
    In normal search response is a FHIR searchset Bundle.  Each
      Bundle entry comprises a ""DocumentReference (mode:#match)"" containing 
      the formatted screening summary, AND a ""Patient (mode:#include)"" 
      instance for the patient demographic detail
  end note

else #Orange No screening summary is available 
SCRAPI -> APIC: ""200 OK"", ""Bundle"" of ""mode: #outcome""
  note over SCRAPI #Orange
    When screening history not available for specified subject, the Bundle contains one
    or more //OperationOutcome//s (""mode: #outcome"") describing the reason(s).
    end note
else #Red technical error
  SCRAPI -[dashed]x APIC--: HTTP ""4xx|5xx"" error code
  note left of SCRAPI #IndianRed
    In technical error scenarios, the response 
    is just a FHIR ""OperationOutcome""
  end note
end

APIC -> APIC: process results and display to user 

APIC -> USER--: present screening summary / search result

@enduml