@startuml seq-fhir-screening-API-usertermsacceptance

!define COMMON .
!include COMMON/sequence-skinparams.iuml

'scale 300 width
scale 300*500

actor "health practitioner (screening)" as USER
participant "practitioner's APP/PMS" as APIC #Orange

' box "HNZ digital services hub" #WhiteSmoke
'   entity "API auth. server" as ROSIE #IndianRed
'   entity "API gateway" as APIG #IndianRed
' end box

box "HNZ FHIR APIs" #WhiteSmoke
  entity "**screening summary API**" as SCRAPI #LightSalmon
  entity "NHI/HPI API" as NHPIG #LightSalmon
  entity "FHIR forms services" as MAGICFORM
end box

title "Cervical screening API data access - special terms practitioner acceptance flow"

== initialisation and prequisite API checks ==

note over APIC
  <size:20>Refer to authorization sequence diagram
end note

== first time API use by new practitioner/user ==

USER -> APIC++ #YellowGreen: request screening summary for a patient

note right of APIC
  PMS/APP must set up ""Request-Context"":
    """userIdentifier""" - user Id as known/authenticated by the PMS/APP
    """userRole""" - the role of the user as defined by the PMS/APP
    """secondaryIdentifier""" - the user's health organisation as an HPI organisation identifier.
end note

APIC -> SCRAPI++: ""GET"" /**DocumentReference**?<params>

SCRAPI -> SCRAPI: check for existing terms acceptance

group#Orange No current terms-acceptance for this practitioner/user
    
  SCRAPI -> MAGICFORM++: Prepare Terms Acceptance Form 
  
  note right of SCRAPI
    Form is prepared as a FHIR Questionnaire for the 
    current Practitioner and Org (from ""Request-Context"")
  end note

  return Form Url ("magic link")

  SCRAPI -> SCRAPI : Prepare ""OperationOutcome"" 403 response
  
  break#LightBlue Practitioner terms acceptance sub flow
    SCRAPI -> APIC--: HTTP ""403 Forbidden"" error with **magic link**

  note right of APIC
    On receipt of a 403 response, the PMS/APP must check for a link in the FHIR ""OperationOutcome.diagnostics"" property.
    The PMS/APP shall redirect the user's browser to that link to dispay the prepared Terms Acceptance form.
  end note

  APIC -> USER++-- #LightBlue : Display form via browser redirect
   
    USER -> USER: Read form and accept special terms

    USER -> MAGICFORM++ : ""POST /QuestionnaireResponse"" (with Request-Context header)

    note left of MAGICFORM
      ""Request-Context"" custom header must set
        """userIdentifier""" - user Id as known/authenticated by the PMS/APP
        """userRole""" - the role of the user as defined by the PMS/APP
        """secondaryIdentifier""" - the user's health organisation as an HPI organisation identifier.
    end note

    MAGICFORM -> MAGICFORM : Extract and record\nacceptance submission
    MAGICFORM -> USER--: Practitioner terms acceptance complete 
    
    deactivate USER

    ... <size:16>The practitioner/user can now resume the request for screening summaries in the PMS. ...

  end
end

== API request processing can now proceed - see Typical Operation diagram ==

@enduml